 version: '3'

 services:
    dev:
        container_name: ginger_dj
        build:
            context: .
            dockerfile: ./Dockerfile
        command: /bin/sh -c "while sleep 1000; do :; done"
        volumes:
          - ./:/app
          - ~/.gitconfig:/etc/gitconfig
          - ~/.ssh:/root/.ssh
