[settings]
git_url_prefix = "https://github.com/ginger-society/ginger-DJ"
take_snapshots = false

[version]
channel = "Final"
major = 5
minor = 5
patch = 1
revision = 0

[[references]]
file_name = "ginger/__init__.py"
output_type = "Tuple"
variable = "VERSION"

[[references]]
file_name = "pyproject.toml"
output_type = "String"
variable = "version"
