# Generated by Ginger 5.1.dev20240505084220 on 2024-05-05 09:11

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_field",
                    models.CharField(
                        choices=[
                            ("choice1", "choice1"),
                            ("choice2", "choice2"),
                            ("choice3", "choice3"),
                        ],
                        default="choice1",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("bool_field", models.BooleanField(default=True)),
                ("char_field", models.CharField(max_length=50, null=True)),
                ("positive_integer_field", models.PositiveIntegerField(default=0)),
                ("field3", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "test",
            },
        ),
        migrations.CreateModel(
            name="TestAppModel1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_field", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "testAppModel1",
            },
        ),
        migrations.CreateModel(
            name="Many2ManyTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "testModels",
                    models.ManyToManyField(related_name="main_models", to="src.test"),
                ),
                (
                    "crossAppModel",
                    models.ManyToManyField(
                        related_name="cross_app_m2mtest", to="src.testappmodel1"
                    ),
                ),
            ],
            options={
                "db_table": "many2ManyTest",
            },
        ),
    ]
